# Generated by Django 5.2.7 on 2025-11-12 06:58

import ckeditor.fields
import core.utils.file_rename
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('text', models.CharField(blank=True, max_length=250, null=True, verbose_name='какой-то текст')),
                ('rate', models.IntegerField(default=1, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('text', models.CharField(verbose_name='Отзыв')),
                ('phone', models.CharField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название жанра')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=core.utils.file_rename.BookFileRenamer.rename_cover, verbose_name='Обложка книги')),
                ('url', models.CharField(blank=True, help_text='URL (генерируется автоматически)', max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('url', models.CharField(blank=True, help_text='URL (генерируется автоматически)', max_length=255, unique=True, verbose_name='URL')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=core.utils.file_rename.BookFileRenamer.rename_cover, verbose_name='Обложка книги')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.utils.file_rename.BookFileRenamer.rename_file, verbose_name='Файл')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название страницы')),
                ('url', models.SlugField(blank=True, help_text='URL страницы (генерируется автоматически)', max_length=255, verbose_name='URL')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('level', models.PositiveIntegerField(default=0, editable=False)),
                ('lft', models.PositiveIntegerField(default=0, editable=False)),
                ('rght', models.PositiveIntegerField(default=0, editable=False)),
                ('tree_id', models.PositiveIntegerField(default=0, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.page', verbose_name='Родительская страница')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'unique_together': {('url', 'parent')},
            },
        ),
    ]
