# Generated by Django 5.2.7 on 2025-10-20 10:38

import core.utils.file_rename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_book_options_book_cover_image_book_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.file_rename.BookFileRenamer.rename_file, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.file_rename.BookFileRenamer.rename_cover, verbose_name='Обложка книги'),
        ),
    ]
