# Generated by Django 5.2.7 on 2025-10-20 10:40

import core.utils.file_rename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_book_pdf_file_book_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.file_rename.BookFileRenamer.rename_cover, verbose_name='Обложка книги'),
        ),
    ]
